### ISSUE TITLE
higher traffic mixes everything up

### ISSUE THREAD

**Issue by oltdaniel** [victorqribeiro/imageCounter#1]
#### Summary

Every call to an PHP site will be executed in parallel. Imagine the situation, that peoples requests overlap or happen in the same timespan. This will result in losing a certain portion of view counts and data being completly mixed up.

#### Problems

- views can get lost very quickly
- file contents can become garbage really quickly as well

> This is the basic result of using files in an multi-threaded enviornment.

#### Solution

PHP offers file locks [`flock`](https://www.php.net/manual/de/function.flock.php) in order to avoid all of the above problems. Additionally PHP offers the use of flags for `file_put_contents` [as seen here](https://www.php.net/manual/en/function.file-put-contents.php). In this case the `LOCK_EX` flag would avoid causing garbage in the file itself.

**Comment by victorqribeiro** [comment]
Thank you for bringing that to my attention

cd7211c

**Comment by oltdaniel** [comment]
> Thank you for bringing that to my attention
> 
> [cd7211c](https://github.com/victorqribeiro/imageCounter/commit/cd7211c8d9f7b90b41b65036d4f89ba2d656a2a9)

As pointed out in my initial solution, this is not enough. This will fix writing into the counter file, but not the time between reading the current count and updating the content.

Take a deeper look into the linked Documentation of `flock`.

**Comment by victorqribeiro** [comment]
Ok, so what I could gather so far is to lock the file before reading and writing. this is what the new code looks like:

```
$file = "counter.txt";
if (!file_exists($file)) {
  touch($file);
}
$handle = fopen($file, "r+");
if (flock($handle, LOCK_EX)) {
  $counter = fread($handle, filesize($file)) ?? 0;
  $counter = intval($counter) + 1;
  ftruncate($handle, 0);
  rewind($handle);
  fwrite($handle, $counter);
  flock($handle, LOCK_UN);
} else {
  die('Could not open file');
}
fclose($handle);
```

**Comment by oltdaniel** [comment]
This should be it, nearly. Because now the complete access to the file during updating is locked, but `fwrite` does not include the sync process of waiting for the whole write process to finish. Do the following change:

```diff
  fwrite($handle, $counter);
+ fflush($handle);
```

With these changes, the following code would be the final version:
```php
$file = "counter.txt";
if (!file_exists($file)) {
  touch($file);
}
// opening file in r/w mode
$handle = fopen($file, "r+");
// following lock functions will block until released (except php exec timeout reached)
if (flock($handle, LOCK_EX)) { // exclusive lock will ensure single access to the file
  // increment current counter
  $counter = fread($handle, filesize($file)) ?? 0;
  $counter = intval($counter) + 1;
  // reset file contents
  ftruncate($handle, 0);
  // reset position
  rewind($handle);
  // write new counter value
  fwrite($handle, $counter);
  // ensure whole data of write process is written
  fflush($handle);
  // release lock
  flock($handle, LOCK_UN);
} else {
  die('Could not open file');
}
// close file access for us
fclose($handle);
// ...
```

> **NOTE**: I haven't developed with php for a long time, but these kinds of locking and file access things are the same across dozens of programming languages and standard course material in CS.

**Comment by victorqribeiro** [comment]
although I think the file_put_contents (with lock on write) was better - because the client would get a counter no matter what, I'll close this issue with the proposed solution - the client only get an image if the process can adquire a lock on counter.txt. given that it provides more consistent data.

23b605b

thanks a lot for all the inputs.
